version: "3"
services: 
  buildapps:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes: 
      - /opt:/opt
  myapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - /opt:/opt
    restart: always
    ports:
      - 8080:46850
    depends_on:
      - buildapps
  