version: "3"
services: 
  buildapps:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes: 
      - disk:/opt/test
  myapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - disk:/opt
    restart: always
    ports:
      - 8080:46850
    depends_on:
      - buildapps
volumes:
  disk:
    driver: local