version: "3.2"

services: 
  buildapps:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes: 
      - type: volume
        source: diskd
        target: /tmp
 
  myapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: diskd
        target: /usr/local/tomcat/webapps/
    ports:
      - 46850:8080
    depends_on:
      - buildapps
    environment:
      - CATALINA_HOME=v/usr/local/tomcat
      - PATH=$CATALINA_HOME/bin:$PATH

volumes:
  diskd:
