version: "3.1"

services: 
  building_apps: 
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes: 
      - type: volume
        source: vlm
        target: /opt
  
  my_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: vlm
        target: /opt
    restart: always
    ports:
      - 8080:46850
    depends_on:
      - building_apps
volumes:
  vlm:
    driver: local
  