version: "3"

services: 
  buildapp:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes: 
      - zaeb:/tmp

  myap:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - zaeb:/tmp
    ports:
      - 46850:8080
    depends_on:
      - buildapp
    environment:
      - CATALINA_HOME=/usr/local/tomcat
      - PATH=${CATALINA_HOME}/bin:$PATH

volumes:
  zaeb:
    driver: local
