version: "3.2"
services: 
  buildapps:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes: 
      - type: volume
        source: disk
        target: /opt/boxfuse-sample-java-war-hello/target
  myapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: disk
        target: /usr/local/tomcat/webapps
    restart: always
    ports:
      - 8080:46850
    depends_on:
      - buildapps
volumes:
  disk:
    driver: local