version: "3.2"
services: 
  buildapps:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes: 
      - type: volume
        source: disk
        target: /opt/boxfuse-sample-java-war-hello/target
  myapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: disk
        target: /usr/local/tomcat/webapps
    ports:
      - 46850:8080
    depends_on:
      - buildapps
volumes:
  disk:
    driver: local