version: "3"
services: 
  building_apps:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes: 
      - /opt:/opt
  my_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - /opt:/opt
    restart: always
    ports:
      - 8080:46850
    depends_on:
      - building_apps
  