version: "3"
services: 
  buildapps:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes: 
      - vlm:/opt/vol1
  myapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - vlm:/opt/vol2
    restart: always
    ports:
      - 8080:46850
    depends_on:
      - buildapps
volumes:
  vlm: