version: "3"

services: 
  buildapps:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes: 
      - vlm1:/tmp

  myapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - vlm1:/opt
    ports:
      - 46850:8080
    depends_on:
      - buildapps
    environment:
      - CATALINA_HOME=v/usr/local/tomcat
      - PATH=$CATALINA_HOME/bin:$PATH

volumes:
  vlm1:
