version: "3"
services: 
  buildapps:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes: 
      - disk1:/opt/boxfuse-sample-java-war-hello
  myapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - disk1:/opt/usr/local/tomcat/
    restart: always
    ports:
      - 8080:46850
    depends_on:
      - buildapps
volumes:
  disk1:
    external: true
    name: disk