version: "3.2"

services: 
  buildapps:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes: 
      - type: volume
        source: vlm1
        target: /tmp
 
  myapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: vlm1
        target: /opt
    ports:
      - 46850:8080
    depends_on:
      - buildapps
    environment:
      - CATALINA_HOME=v/usr/local/tomcat
      - PATH=$CATALINA_HOME/bin:$PATH

volumes:
  vlm1:
